debug: false

spring:
  datasource:
    auth:
      url: jdbc:postgresql://localhost:5432/testero_auth
      username: testero_auth
      password: testero_auth
      driver-class-name: org.postgresql.Driver

    core:
      url: jdbc:postgresql://localhost:5432/testero_core
      username: testero_core
      password: testero_core
      driver-class-name: org.postgresql.Driver

    resp:
      url: jdbc:postgresql://localhost:5432/testero_resp
      username: testero_resp
      password: testero_resp
      driver-class-name: org.postgresql.Driver

#  main:
#    allow-bean-definition-overriding: false

  graphql:
    path: /graphql
    graphiql:
      enabled: false


